# Generated by Django 5.0.1 on 2024-01-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nn', 'None'), ('Dr', 'Doctor'), ('Lw', 'Lawyer'), ('Cl', 'Cleaner'), ('Cr-Rp', 'Car-Repairman'), ('Ph-Rp', 'Phone-Repairman'), ('Cp-Rp', 'Computer-Repairman'), ('El-Rp', 'Electricity-Repairman'), ('Ht-Rp', 'Heating-Repairman')], default='Nn', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('in-place', 'In Place')], default='online', max_length=25)),
            ],
        ),
    ]
