# Generated by Django 5.0.1 on 2024-01-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_app',
            old_name='name',
            new_name='service',
        ),
    ]
