# Generated by Django 5.0.1 on 2024-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=600)),
                ("city", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=150)),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="backend/media/consultation/%Y/%m/%d/"
                    ),
                ),
                ("bio", models.TextField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                            ("Bussy", "Bussy"),
                        ],
                        default="Offline",
                        max_length=10,
                    ),
                ),
                (
                    "typeOfService",
                    models.CharField(
                        choices=[
                            ("ByPhone", "Byphone"),
                            ("ByText", "Bytext"),
                            ("InPlace", "Inplace"),
                            ("OnPlace", "Onplace"),
                        ],
                        default="ByText",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
